name: CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Ubuntu CI
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        backend: [Pulseaudio, Portaudio, Gr-audio]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y cmake qt5-default libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev gr-osmosdr gr-fcdproplus liborc-0.4-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: mkdir build && cd build && cmake -DLINUX_AUDIO_BACKEND:STRING=${{ matrix.backend }} ..
      - name: Compile
        working-directory: build
        run: make
  macos-build:
    name: MacOS CI
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        backend: [Portaudio, Gr-audio]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: brew install gr-osmosdr
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: mkdir build && cd build && cmake -DOSX_AUDIO_BACKEND:STRING=${{ matrix.backend }} ..
      - name: Compile
        working-directory: build
        run: make
